class MainSection < SitePrism::Section

  element :abtest, 							:xpath, "//*//li[1]/a"
  element :basicauth, 					:xpath, "//*//li[2]/a"
  element :brokeimage, 					:xpath, "//*//li[3]/a"
  element :dom, 								:xpath, "//*//li[4]/a"
  element :checkbox, 						:xpath, "//*//li[5]/a"
  element :contmenu, 						:xpath, "//*//li[6]/a"
  element :disselement, 				:xpath, "//*//li[7]/a"
  element :dragdrop, 						:xpath, "//*//li[8]/a"
  element :dropwdown, 					:xpath, "//*//li[9]/a"
  element :dynamicontent, 			:xpath, "//*//li[10]/a"
  element :dynamicontrol, 			:xpath, "//*//li[11]/a"
  element :dynamicload,         :xpath, "//*//li[12]/a"
  element :exitintent,         :xpath, "//*//li[13]/a"
  element :fdownload, 					:xpath, "//*//li[14]/a"
  element :fupload, 						:xpath, "//*//li[15]/a"
  element :floatmenu, 					:xpath, "//*//li[16]/a"
  element :forgotpass, 					:xpath, "//*//li[17]/a"
  element :formauthen, 					:xpath, "//*//li[18]/a"
  element :frames, 							:xpath, "//*//li[19]/a"
  element :geolocation, 				:xpath, "//*//li[20]/a"
  element :hovers, 							:xpath, "//*//li[21]/a"
  element :infinitescroll, 			:xpath, "//*//li[22]/a"
  element :jquerymenu, 					:xpath, "//*//li[23]/a"
  element :jsalert, 						:xpath, "//*//li[24]/a"
  element :jsonload, 						:xpath, "//*//li[25]/a"
  element :keypress, 						:xpath, "//*//li[26]/a"
  element :largedeep, 					:xpath, "//*//li[27]/a"
  element :multiplewind, 				:xpath, "//*//li[28]/a"
  element :nestedframe, 				:xpath, "//*//li[29]/a"
  element :notification, 				:xpath, "//*//li[30]/a"
  element :redirectlink, 				:xpath, "//*//li[31]/a"
  element :securedownload, 			:xpath, "//*//li[32]/a"
  element :shiftcontent, 				:xpath, "//*//li[33]/a"
  element :slowresource, 				:xpath, "//*//li[34]/a"
  element :sortabledata, 				:xpath, "//*//li[35]/a"
  element :statuscode, 					:xpath, "//*//li[36]/a"
  element :typos, 							:xpath, "//*//li[37]/a"
  element :wysiwyg, 						:xpath, "//*//li[38]/a"
end 

class MainPage < SitePrism::Page
  set_url '/'
	section :main_section, MainSection, :xpath, "/html/body"
end

